name: buildpack
on: [push, pull_request]
jobs:
  dockerhub_remote_build:
    runs-on: ubuntu-latest
    container:
      image: docker:stable
      volumes:
        - /home/runner:/var/www
    env:
      IMG_NAME: "<SOME_IMG>"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: andrioid/setup-pack@master
      - run: pack build andridk --builder heroku/buildpacks:20
