name: Deploy to Fly.io

on:
  workflow_call:
    inputs:
      app_name:
        type: string
        description: "Name of the Fly app"
        required: true
      image:
        type: string
        description: "Image to pull and deploy"
        default: latest
    secrets:
      FLY_API_TOKEN:
        required: true
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  IMAGE_GHCR: ${{ inputs.image }}
  IMAGE_FLY: registry.fly.io/${{ inputs.app_name }}:${{ github.sha }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: flyctl auth docker
      - run: docker pull ${{ env.IMAGE_GHCR }}
      - run: docker tag ${{ env.IMAGE_GHCR }} ${{ env.IMAGE_FLY }}
      - run: docker push ${{ env.IMAGE_FLY }}
      - run: flyctl deploy --image ${{ env.IMAGE_FLY }} --app ${{ inputs.app_name }}
