name: Deploy to Fly.io

on:
  workflow_call:
    inputs:
      app_name:
        type: string
        description: "Name of the Fly app"
        required: true
      image:
        type: string
        description: "Image to pull and deploy"
        required: true
    secrets:
      FLY_API_TOKEN:
        required: true
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - run: flyctl deploy --app ${{ inputs.app_name }} --image ${{ inputs.image }}
