name: Deploy to Ogre

on:
  workflow_call:
    secrets:
      GITOPS_HOST:
        required: true
      GITOPS_USER:
        required: true
      OGRE_GITOPS_KEY:
        required: true
      OGRE_GITOPS_HOST_FINGERPRINT:
        required: true
env:
  GITOPS_HOST: ${{ secrets.GITOPS_HOST }}
  GITOPS_USER: ${{ secrets.GITOPS_USER }}
  OGRE_GITOPS_KEY: ${{ secrets.OGRE_GITOPS_KEY }}
  OGRE_GITOPS_HOST_FINGERPRINT: ${{ secrets.OGRE_GITOPS_HOST_FINGERPRINT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$OGRE_GITOPS_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$OGRE_GITOPS_HOST_FINGERPRINT" >> ~/.ssh/known_hosts
      - name: SSH Command Runner
        run: |
          ssh gitops@ogre.scrolls.org << 'EOF'
              set -e
              set -x
              set-container andridk "{{ github.sha}}"
          EOF
