name: Fly Deploy
on:
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: registry.fly.io/andridk:${{ github.sha }}
          build-args: |
            MODEL_BOX_API_KEY=${{ secrets.MODEL_BOX_API_KEY }}
      - run: flyctl deploy --image registry.fly.io/andridk:${{ github.sha }}

  # deploy:
  #   name: Deploy app
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: superfly/flyctl-actions/setup-flyctl@master
  #     - run: flyctl deploy --remote-only
