name: Build & Deploy
on:
  push:
    branches:
      - master
  workflow_call:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository}}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      MODEL_BOX_API_KEY: ${{ secrets.MODEL_BOX_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - run: flyctl auth docker
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            registry.fly.io/andridk
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            ${{ github.sha }}
      - uses: jdx/mise-action@v2
      - name: Dependencies & Build
        run: npm ci && npm run build
      - uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy-fly:
    name: Deploy to Fly.io
    needs: build
    uses: ./.github/workflows/deploy-fly.yml
    with:
      app_name: andridk
      image: ${{ needs.build.outputs.image }}
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy-ogre:
    name: Deploy to Ogre
    needs: build
    uses: ./.github/workflows/deploy-ogre.yml
    secrets:
      GITOPS_HOST: ${{ secrets.GITOPS_HOST }}
      GITOPS_USER: ${{ secrets.GITOPS_USER }}
      OGRE_GITOPS_KEY: ${{ secrets.OGRE_GITOPS_KEY }}
      OGRE_GITOPS_HOST_FINGERPRINT: ${{ secrets.OGRE_GITOPS_HOST_FINGERPRINT }}
  md-social:
    name: md-social
    needs:
      - deploy-fly
      - deploy-ogre
    runs-on: ubuntu-latest
    env:
      BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
      BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
      MD_BASE_URL: https://andri.dk/blog
      PUBLISH_MAX_DAYS: 7
      VERBOSE: 1
      BASE_URL: https://andri.dk/blog
      OG_IMAGE_BG: public/img/gradient.svg
      OG_IMAGE_AUTHOR: public/img/coffee-art.jpg
      OG_DEST_DIR: public/img/social

    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: |
          sudo apt-get update
          sudo apt-get install -y fontconfig fonts-ubuntu
      - run: npm ci
      - run: npm run md-social
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "md-social update" || exit 0
          git push
